fix(core): fix workflow.

diff --git a/.github/workflows/release-uvx.yml b/.github/workflows/release-uvx.yml
--- a/.github/workflows/release-uvx.yml
+++ b/.github/workflows/release-uvx.yml
@@ -2,8 +2,8 @@ name: Release (uvx)
 
 on:
   push:
-    branches:
-      - master # Si attiva quando fai il merge su master
+    tags:
+      - 'v[0-9]+.[0-9]+.[0-9]+' # push di una versione canonica (es. v1.2.3) senza pre-release
 
 permissions:
   contents: write
@@ -12,7 +12,7 @@ permissions:
 
 jobs:
   build-release:
-    if: startsWith(github.ref, 'refs/tags/')
+    if: ${{ github.ref == 'refs/heads/master' }}
     runs-on: ubuntu-latest
 
     steps:
@@ -20,6 +20,15 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Carica tutta la cronologia per poter confrontare i rami
+
+      - name: Check if tag is on master
+        run: |
+          # Controlla se il tag (GITHUB_REF) è contenuto nel branch master
+          git fetch origin master
+          if ! git branch -r --contains ${{ github.ref }} | grep -q "origin/master"; then
+            echo "Tag ${{ github.ref }} is not on master branch. Aborting release."
+            exit 1
+          fi
 
       - name: Set up Python
         uses: actions/setup-python@v5
